version: '3.8'

services:
  service-discovery:
    build:
      context: .
      dockerfile: Dockerfile-discovery
    ports:
      
"8761:8761"
  networks:
microservices-net

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile-gateway
    ports:
      
"8080:8080"
  depends_on:
service-discovery
environment:
EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
networks:
microservices-net

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile-auth
    ports:
      
"8081:8081"
  depends_on:
service-discovery
environment:
EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
networks:
microservices-net

  pedido-service:
    build:
      context: .
      dockerfile: Dockerfile-pedido
    ports:
      
"8082:8082"
  depends_on:
service-discovery
environment:
EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
networks:
microservices-net

  pagamento-service:
    build:
      context: .
      dockerfile: Dockerfile-pagamento
    ports:
      
"8083:8083"
  depends_on:
service-discovery
environment:
EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka/
networks:
microservices-net

networks:
  microservices-net:
    driver: bridge
